# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
## 1
## Array Creation and Manipulation

import numpy as np

# Membuat array 2D dengan ukuran (5, 5) dan angka random antara 1 dan 20
satu = np.random.randint(1, 21, size=(5, 5))
print("Array sebelum modifikasi:")
print(satu)

# Mengganti semua nilai pada kolom ketiga dengan 1
satu[:, 2] = 1  # : berarti semua baris, 2 adalah indeks kolom ketiga (indeks dimulai dari 0)

print("\nArray setelah modifikasi:")
print(satu)

# Membuat array 2D dengan ukuran (4, 4) dan angka random antara 1 dan 16
dua = np.random.randint(1,17, size=(4,4))
print("\nArray Kedua Sebelum Dimodifikasi:\n",dua)

# Mengganti semua nilai diagonal menjadi 0
np.fill_diagonal(dua,0)
print("\nArray Kedua Setelah Dimodifikasi:\n",dua)



Array sebelum modifikasi:
[[ 3  4 13 20  3]
 [12 20 18 10 19]
 [ 2  9 14 13  9]
 [ 3  7  5 16 15]
 [11  9 13  6 10]]

Array setelah modifikasi:
[[ 3  4  1 20  3]
 [12 20  1 10 19]
 [ 2  9  1 13  9]
 [ 3  7  1 16 15]
 [11  9  1  6 10]]

Array Kedua Sebelum Dimodifikasi:
 [[ 4 15  4  8]
 [ 2  2  1  1]
 [ 9 11  8 11]
 [ 7  2 10  6]]

Array Kedua Setelah Dimodifikasi:
 [[ 0 15  4  8]
 [ 2  0  1  1]
 [ 9 11  0 11]
 [ 7  2 10  0]]


In [3]:
## 2
## Array Indexing & Slicing
print("Array:")
duwa = np.arange(1,37).reshape((6,6))
print(duwa)
sub_array = duwa[2:5, 1:4]
print("\n=============================")
print("Sub-array:")
print(sub_array)



duwain = np.random.randint(1,100,size=(5,5))
print(duwain)

print("\n=============================")
border_elements = np.concatenate((duwain[0, :], duwain[-1, :], duwain[1:-1, 0], duwain[1:-1, -1]))
print("Border elements:")
print(border_elements)

Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[64 46 90 69 37]
 [78 29  3 26 91]
 [31 16 36 81 53]
 [92 95 95 52 33]
 [40 70 42  8 26]]

Border elements:
[64 46 90 69 37 40 70 42  8 26 78 31 92 91 53 33]


In [4]:
## 3
## Array Operations

print("Array 1: ")
tiga = np.random.randint(1,11,size=(3,4))
print(tiga)
print("==============================")
print("Array 2: ")
tiga2 = np.random.randint(1,11,size=(3,4))
print(tiga2)
print("\n============================")
print("Additon: ")
addition = tiga + tiga2
print(addition)
print("\n============================")
print("Substraction: ")
substraction = tiga - tiga2
print(substraction)
print("\n============================")
print("Multiplication: ")
multiplication = tiga * tiga2
print(multiplication)
print("\n============================")
print("Divison: ")
division = tiga / tiga2
print(division)

Array 1: 
[[ 8  3  5  5]
 [ 9  1  9 10]
 [ 9  7 10  5]]
Array 2: 
[[ 8  3  1  1]
 [ 9 10  6  3]
 [ 5  8  7  8]]

Additon: 
[[16  6  6  6]
 [18 11 15 13]
 [14 15 17 13]]

Substraction: 
[[ 0  0  4  4]
 [ 0 -9  3  7]
 [ 4 -1  3 -3]]

Multiplication: 
[[64  9  5  5]
 [81 10 54 30]
 [45 56 70 40]]

Divison: 
[[1.         1.         5.         5.        ]
 [1.         0.1        1.5        3.33333333]
 [1.8        0.875      1.42857143 0.625     ]]


In [5]:
## 4
## Statistical Operations

four = np.random.randint(1,11,size=(5,5))
print(four)

print("==================================")
print(f"Rata-rata: {np.mean(four)}")
print(f"Median: {np.mean(four)}")
print(f"Standard Deviasi: {np.std(four)}")
print(f"Varinasa: {np.var(four)}")
print(f"Jumlah: {np.sum(four)}")

[[ 4  1  4  9  9]
 [ 1  6  8  3  8]
 [ 8 10  6 10  2]
 [ 3  8  3  8  6]
 [ 9  1  3  7  4]]
Rata-rata: 5.64
Median: 5.64
Standard Deviasi: 2.9377542443165665
Varinasa: 8.630400000000002
Jumlah: 141


In [6]:
## 5
## Broadcasting

lima = np.random.randint(1,10,size=(3,3))
print(f"Array:\n {lima}")

lima2 = np.random.randint(1,10,size=(3,))
print(f"\nArray:\n {lima2}")


print("\n Jawaban:")
add = lima + lima2  #addition
print(add)


lima3 = np.random.randint(1,10,size=(4,4))
print(f"\nArray 3:\n {lima3}")


lima4 = np.random.randint(1,10,size=(4,))
print(f"\nArray 4:\n {lima4}")


print("\n Jawaban:")
sub = lima3 - lima4 #substraction
print(sub)



Array:
 [[8 5 5]
 [3 6 8]
 [5 4 8]]

Array:
 [7 7 1]

 Jawaban:
[[15 12  6]
 [10 13  9]
 [12 11  9]]

Array 3:
 [[1 2 1 3]
 [8 5 3 2]
 [2 3 3 8]
 [2 5 9 6]]

Array 4:
 [5 5 4 1]

 Jawaban:
[[-4 -3 -3  2]
 [ 3  0 -1  1]
 [-3 -2 -1  7]
 [-3  0  5  5]]


In [12]:
## 6
## 

enam = np.random.randint(1,10,size=(3,3))
print(enam)

# menemukan determinan
determine = np.linalg.det(enam)
print(determine)

## inverse
inverse = np.linalg.inv(enam)
print(inverse)

## eigenvalues
eigenvalues = np.linalg.eig(enam)
print(eigenvalues)

[[3 5 1]
 [8 5 1]
 [7 2 6]]
-139.99999999999994
[[-2.00000000e-01  2.00000000e-01  2.60208521e-18]
 [ 2.92857143e-01 -7.85714286e-02 -3.57142857e-02]
 [ 1.35714286e-01 -2.07142857e-01  1.78571429e-01]]
EigResult(eigenvalues=array([11.81110697, -2.51817897,  4.70707199]), eigenvectors=array([[-0.41179652, -0.65655074, -0.11230775],
       [-0.58612249,  0.64707134, -0.23160458],
       [-0.69777078,  0.38760779,  0.96630548]]))


In [ ]:
enam1 = np.random.randint(1,10,size=(2,3))
enam2 = np.random.randint(1,10,size=(3,3))

print(f"Matrix 1: \n",enam1)
print(f"\nMatrix 2: \n",enam2)

multiplicationn = np.dot(enam1,enam2) #multiplication
print(f"\n Multiplication Result: \n",multiplicationn)

Matrix 1: 
 [[9 6 6]
 [5 6 8]]

Matrix 2: 
 [[6 3 5]
 [6 8 5]
 [5 5 8]]

 Multiplication Result: 
 [[120 105 123]
 [106 103 119]]
