# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
## 1
## Array Creation and Manipulation

import numpy as np

# Membuat array 2D dengan ukuran (5, 5) dan angka random antara 1 dan 20
satu = np.random.randint(1, 21, size=(5, 5))
print("Array sebelum modifikasi:")
print(satu)

# Mengganti semua nilai pada kolom ketiga dengan 1
satu[:, 2] = 1  # : berarti semua baris, 2 adalah indeks kolom ketiga (indeks dimulai dari 0)

print("\nArray setelah modifikasi:")
print(satu)

# Membuat array 2D dengan ukuran (4, 4) dan angka random antara 1 dan 16
dua = np.random.randint(1,17, size=(4,4))
print("\nArray Kedua Sebelum Dimodifikasi:\n",dua)

# Mengganti semua nilai diagonal menjadi 0
np.fill_diagonal(dua,0)
print("\nArray Kedua Setelah Dimodifikasi:\n",dua)



Array sebelum modifikasi:
[[18 20 19 11 13]
 [ 5 10 17 12 14]
 [14 18 14 10 13]
 [18 17  5  8 19]
 [ 4  1  4 14  9]]

Array setelah modifikasi:
[[18 20  1 11 13]
 [ 5 10  1 12 14]
 [14 18  1 10 13]
 [18 17  1  8 19]
 [ 4  1  1 14  9]]

Array Kedua Sebelum Dimodifikasi:
 [[ 9 16 16  8]
 [11 15 11 12]
 [ 6 14  3  3]
 [16  6  2 13]]

Array Kedua Setelah Dimodifikasi:
 [[ 0 16 16  8]
 [11  0 11 12]
 [ 6 14  0  3]
 [16  6  2  0]]


In [30]:
## 2
## Array Indexing & Slicing
print("Array:")
duwa = np.arange(1,37).reshape((6,6))
print(duwa)
sub_array = duwa[2:5, 1:4]
print("\n=============================")
print("Sub-array:")
print(sub_array)



duwain = np.random.randint(1,100,size=(5,5))
print(duwain)

print("\n=============================")
border_elements = np.concatenate((duwain[0, :], duwain[-1, :], duwain[1:-1, 0], duwain[1:-1, -1]))
print("Border elements:")
print(border_elements)

Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[63 74 94 91 81]
 [16 84 72 64 81]
 [12 23 22 45 16]
 [23 29 53 66 84]
 [97 68 76 93 86]]

Border elements:
[63 74 94 91 81 97 68 76 93 86 16 12 23 81 16 84]


In [44]:
## 3
## Array Operations

print("Array 1: ")
tiga = np.random.randint(1,11,size=(3,4))
print(tiga)
print("==============================")
print("Array 2: ")
tiga2 = np.random.randint(1,11,size=(3,4))
print(tiga2)
print("\n============================")
print("Additon: ")
addition = tiga + tiga2
print(addition)
print("\n============================")
print("Substraction: ")
substraction = tiga - tiga2
print(substraction)
print("\n============================")
print("Multiplication: ")
multiplication = tiga * tiga2
print(multiplication)
print("\n============================")
print("Divison: ")
division = tiga / tiga2
print(division)

Array 1: 
[[3 4 6 5]
 [1 1 9 7]
 [4 6 6 1]]
Array 2: 
[[ 6  4  7  8]
 [10 10  6  8]
 [ 7  9  9 10]]

Additon: 
[[ 9  8 13 13]
 [11 11 15 15]
 [11 15 15 11]]

Substraction: 
[[-3  0 -1 -3]
 [-9 -9  3 -1]
 [-3 -3 -3 -9]]

Multiplication: 
[[18 16 42 40]
 [10 10 54 56]
 [28 54 54 10]]

Divison: 
[[0.5        1.         0.85714286 0.625     ]
 [0.1        0.1        1.5        0.875     ]
 [0.57142857 0.66666667 0.66666667 0.1       ]]


In [50]:
## 4
## Statistical Operations

four = np.random.randint(1,11,size=(5,5))
print(four)

print("==================================")
print(f"Rata-rata: {np.mean(four)}")
print(f"Median: {np.mean(four)}")
print(f"Standard Deviasi: {np.std(four)}")
print(f"Varinasa: {np.var(four)}")
print(f"Jumlah: {np.sum(four)}")

[[1 6 9 1 4]
 [6 2 2 2 2]
 [8 3 9 5 6]
 [1 1 8 2 6]
 [5 3 7 3 8]]
Rata-rata: 4.4
Median: 4.4
Standard Deviasi: 2.6832815729997477
Varinasa: 7.2
Jumlah: 110


In [77]:
## 5
## Broadcasting

lima = np.random.randint(1,10,size=(3,3))
print(f"Array:\n {lima}")

lima2 = np.random.randint(1,10,size=(3,))
print(f"\nArray:\n {lima2}")


print("\n Jawaban:")
add = lima + lima2  #addition
print(add)


lima3 = np.random.randint(1,10,size=(4,4))
print(f"\nArray 3:\n {lima3}")


lima4 = np.random.randint(1,10,size=(4,))
print(f"\nArray 4:\n {lima4}")


print("\n Jawaban:")
sub = lima3 - lima4 #substraction
print(sub)



Array:
 [[8 9 3]
 [6 4 8]
 [4 6 4]]

Array:
 [9 3 6]

 Jawaban:
[[17 12  9]
 [15  7 14]
 [13  9 10]]

Array 3:
 [[8 8 9 7]
 [3 4 6 2]
 [1 2 9 3]
 [7 6 6 8]]

Array 4:
 [8 9 4 4]

 Jawaban:
[[ 0 -1  5  3]
 [-5 -5  2 -2]
 [-7 -7  5 -1]
 [-1 -3  2  4]]


In [ ]:
## 6
## 