### NUMPY IN PYTHON
NumPy adalah sebuah library di Python yang digunakan untuk komputasi ilmiah. Library ini menyediakan dukungan untuk array besar multidimensi dan matriks, bersama dengan berbagai fungsi matematika tingkat tinggi untuk operasi pada array tersebut. NumPy sangat efisien dan digunakan secara luas dalam bidang data science, machine learning, dan komputasi ilmiah lainnya.


In [3]:
!pip install numpy

In [4]:
import numpy as np #create array using numpy   
arr1 = np.array([1,2,3,4,5]) # create array 1D
print(arr1,type(arr1))
print(arr1.shape) #melihat jumlah bari & kolom pada list

[1 2 3 4 5] <class 'numpy.ndarray'>
(5,)


### SHAPE & RESHAPE

Shape digunakan untuk mengecek baris dan kolom dari sebuah list, 
Reshape digunakan untuk membuat baris list menjadi 1D, 2D atau 3D

In [5]:
# reshape
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #hasil nya array 2D yaitu 1 row & 5 column


array([[1, 2, 3, 4, 5]])

In [6]:
## 2D Array
arr2 = np.array([[1,2,3,4,5,6]])
arrayreshapedd = arr2.reshape(2,3) #mengubah array 1D menjadi 2 baris & 3 kolom
print(arrayreshapedd)  

[[1 2 3]
 [4 5 6]]


In [7]:
np.arange(0,10,2) #membuat array dengan range

array([0, 2, 4, 6, 8])

In [8]:
np.arange(0,10,2).reshape(5,1) #mereshape list menjadi 5 bari dan 1 kolom

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4)) #membuat array 2D dan mengisi elemennya menjadi 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
#identify matrix

np.eye(3) #membuat matriks identitas selain diagoanal berisikan 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
matriks = np.eye(3, k=1)  # Diagonal digeser 1 langkah ke atas
print(matriks)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [12]:
matriks = np.eye(3, dtype=int)  # Tipe data integer
print(matriks)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [13]:
arr = np.array([[1,2,3],[4,5,6]])
print(f"Array:\n",arr)
print(f"Shape:",arr.shape)
print(f"Number of Dimensions:",arr.ndim)
print(f"Size (number of elements):",arr.size)
print("Data Type:",arr.dtype)
print(f"Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
Size (number of elements): 6
Data Type: int64
Item size (in bytes): 8


In [14]:
## Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("Addition:",arr1+arr2)

## Element Wise Substraction
print("Substraction:",arr1-arr2)

## Element Wise Multiplication
print("Multiplication:",arr1*arr2)

## Element Wose Division
print("Division:",arr1/arr2)


Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [15]:
## Universal Function

arr = np.array([1,2,3,4,5,6])

# square root (akar 2)
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine (sinus)
print(np.sin(arr))

## Natural Log (logaritma)
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [16]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr) 

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr[0][0] #menampilkan array baris 0 kolom 0

np.int64(1)

In [ ]:
arr[2:] #menampilkan semua element baris ketiga

array([[ 9, 10, 11, 12]])

In [ ]:
arr[1:,2:] # menampilkan dari baris 1 indeks 1 hingga baris 2 ideks 2 seterusnya

array([[ 7,  8],
       [11, 12]])

In [25]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [26]:
## Modify Array Elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
arr[1:]=100 #modifikasi baris 1 seterusnya menjadi 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [32]:
## Statistical Concepts -- Normalization --
## To have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Calculate the mean and standard deviation
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data-mean) / std_dev
print("Normalized Data: ",normalized_data)

Normalized Data:  [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [34]:
print(f"Data: {data}")
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Std_Dev: {std_dev}")
print(f"normalized_data: {normalized_data}")

Data: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Median: 5.5
Std_Dev: 2.8722813232690143
normalized_data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [ ]:
## Logical Operation

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5)&(data<=8)] #menampilkan data mulai dari 5 hingga 8

array([5, 6, 7, 8])